Remove META-INF/services/org.apache.xerces.xni.parser.XMLParserConfiguration from xercesImpl.jar. xercesImpl.jar should not contain a META-INF/services entry indicating which configuration the parser should use. It prevents applications further down the classpath from overriding the parser's default and may also cause an incompatible mix of classes to be loaded leading to a failure such as a NoSuchMethodError.
git-svn-id: https://svn.apache.org/repos/asf/xerces/java/trunk@320467 13f79535-47bb-0310-9956-ffa450edef68