This fix tested the case where we have an incorrect UTF-8 mutibyte such any of the following sequences: f0 90 80 5f f4 8f bf 5f f2 8f bf 20
This came about as the parser did not detect errors with testcase ibm02v01.xml
( without revisions ).

The same tescase produces and error message with Microsoft XML parser.

I check that the  multibyte followed Table A-3 from Unicode UTF-8 bit distribution.

This causes the line and problem to be reported, but we still have a bug because
in this case we then call scanInvalidChar and convert the invalid UTF-8 into a Unicode
value which we report in the message.

element  = prefix: -1, localpart: 37, rawname: 37, uri: -1
[Fatal Error] ibm02v01.xml:7:50: An invalid XML character (Unicode: 0x1001f) was
 found in the processing instruction.
org.xml.sax.SAXException: Stopping after fatal error: An invalid XML character (
Unicode: 0x1001f) was found in the processing instruction.

Here value f0 90 80 5f (incorrect UTF-8) was mapped incorrectly into 0x1001F !! This is bad





PR:
Obtained from:
Submitted by:
Reviewed by:


git-svn-id: https://svn.apache.org/repos/asf/xerces/java/trunk@315974 13f79535-47bb-0310-9956-ffa450edef68